const data = [
  { id: "a8", class: "square", starterPiece: "rook" },
  { id: "b8", class: "square grey", starterPiece: "knight" },
  { id: "c8", class: "square", starterPiece: "bishop" },
  { id: "d8", class: "square grey", starterPiece: "king" },
  { id: "e8", class: "square", starterPiece: "queen" },
  { id: "f8", class: "square grey", starterPiece: "bishop" },
  { id: "g8", class: "square", starterPiece: "knight" },
  { id: "h8", class: "square grey", starterPiece: "rook" },

  { id: "a7", class: "square grey", starterPiece: "pawn" },
  { id: "b7", class: "square", starterPiece: "pawn" },
  { id: "c7", class: "square grey", starterPiece: "pawn" },
  { id: "d7", class: "square", starterPiece: "pawn" },
  { id: "e7", class: "square grey", starterPiece: "pawn" },
  { id: "f7", class: "square", starterPiece: "pawn" },
  { id: "g7", class: "square grey", starterPiece: "pawn" },
  { id: "h7", class: "square", starterPiece: "pawn" },

  { id: "a6", class: "square" },
  { id: "b6", class: "square grey" },
  { id: "c6", class: "square" },
  { id: "d6", class: "square grey" },
  { id: "e6", class: "square" },
  { id: "f6", class: "square grey" },
  { id: "g6", class: "square" },
  { id: "h6", class: "square grey" },

  { id: "a5", class: "square grey" },
  { id: "b5", class: "square" },
  { id: "c5", class: "square grey" },
  { id: "d5", class: "square" },
  { id: "e5", class: "square grey" },
  { id: "f5", class: "square" },
  { id: "g5", class: "square grey" },
  { id: "h5", class: "square" },

  { id: "a4", class: "square" },
  { id: "b4", class: "square grey" },
  { id: "c4", class: "square" },
  { id: "d4", class: "square grey" },
  { id: "e4", class: "square" },
  { id: "f4", class: "square grey" },
  { id: "g4", class: "square" },
  { id: "h4", class: "square grey" },

  { id: "a3", class: "square grey" },
  { id: "b3", class: "square" },
  { id: "c3", class: "square grey" },
  { id: "d3", class: "square" },
  { id: "e3", class: "square grey" },
  { id: "f3", class: "square" },
  { id: "g3", class: "square grey" },
  { id: "h3", class: "square" },

  { id: "a2", class: "square", starterPiece: "pawn" },
  { id: "b2", class: "square grey", starterPiece: "pawn" },
  { id: "c2", class: "square", starterPiece: "pawn" },
  { id: "d2", class: "square grey", starterPiece: "pawn" },
  { id: "e2", class: "square", starterPiece: "pawn" },
  { id: "f2", class: "square grey", starterPiece: "pawn" },
  { id: "g2", class: "square", starterPiece: "pawn" },
  { id: "h2", class: "square grey", starterPiece: "pawn" },

  { id: "a1", class: "square grey", starterPiece: "rook" },
  { id: "b1", class: "square", starterPiece: "knight" },
  { id: "c1", class: "square grey", starterPiece: "bishop" },
  { id: "d1", class: "square", starterPiece: "king" },
  { id: "e1", class: "square grey", starterPiece: "queen" },
  { id: "f1", class: "square", starterPiece: "bishop" },
  { id: "g1", class: "square grey", starterPiece: "knight" },
  { id: "h1", class: "square", starterPiece: "rook" },
];

export default data;
